# http response status codes and descriptions
OK = 200
BAD_REQUEST = 400
BAD_REQUEST_MSG = "Bad Request"
UNAUTHORIZED = 401
UNAUTHORIZED_MSG = "Unauthorized"
FORBIDDEN = 403
FORBIDDEN_MSG = "Forbidden"
RESOURCE_NOT_FOUND = 404
RESOURCE_NOT_FOUND_MSG = "Resource Not Found"
UNPROCESSABLE_ENTITY = 422
UNPROCESSABLE_ENTITY_MSG = "Unprocessable Entity"
INTERNAL_SERVER_ERROR = 500
INTERNAL_SERVER_ERROR_MSG = "Unknown Authorization Error"